---
networks:
  ollama-network:
    # external: true # only comment out if you want others in your business
    name: ollama-network
volumes:
  ollama:
    driver: local
  open-webui:
    driver: local
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - ollama-network
    container_name: open-webui
    ports:
      - 3000:8080
    # environment:
    #   - OLLAMA_BASE_URL=NETWORK_ADDRESS:11434 # for others to consume
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
  ollama:
    image: ollama/ollama
    networks:
      - ollama-network
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    command:
      - serve
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    restart: unless-stopped

# TODO add https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Setup